baseURL = "https://techvoterguide.com/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Tech Worker Voter Guide"
theme = "hugo-theme-techdoc"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]

    # Souce Code repository section
    description = "Because they're going to blame you whether or not you vote."
    github_repository = "https://github.com/sbuss/tech-worker-voter-guide"
    version = "0.0.1"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

[taxonomies]
category = "categories"

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Framework"
    url = "/frameworks/"
    weight = 2

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/sbuss"
    weight = 3
